language: python
python:
  - "3.6.7"
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install: pip install selenium
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - cd tests
script:
  - pytest