language: python
python:
  - "3.6.7"
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - cd tests
install: pip install -r requirements.txt
script:
  - pytest